FROM python:3.6
RUN apt-get update && apt-get install -y --no-install-recommends default-mysql-client=1.0.5 dos2unix=7.4.0-1 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/app
COPY requirements.txt .
RUN pip install -r ./requirements.txt
COPY . .

ENV PORT=${PORT:-3000}

EXPOSE ${PORT}
CMD python app.py run -h 0.0.0.0 -p ${PORT}
