# Build HS and DB Containers and run tests.
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Houston Service - CICD Workflow

on:
  push
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    ### Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - name: Extract current branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Echo Branch Name
      shell: bash
      run: |
        echo Branch name: ${{ steps.extract_branch.outputs.branch }}      
    - uses: actions/checkout@v2
      with:
        repository: tranquilitybase-io/tb-houston-service
        path: tb-houston-service
        fetch-depth: 0

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server:  https://gcr.io
        username: '_json_key'
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Build Houston Service Image
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/tb-houston-service
        docker build -t gcr.io/eagle-console-resources/tb-houston-service:ci .
        docker push gcr.io/eagle-console-resources/tb-houston-service:ci

    - name: Start Docker Compose
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/tb-houston-service
        docker-compose -f docker_compose_ci.yml up > docker_compose_ci.log 2>&1 &

    - name: Give Services time to initialize (abort if elapsed time is greater than 10 minutes)
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/tb-houston-service
        start_epoch="$(date -u +%s)"
        elapsed_seconds=0
        until [ $(docker-compose -f docker_compose_ci.yml ps | grep Up | wc -l) -eq 3 ] || [ $elapsed_seconds -ge 600 ]
        do
          sleep 30
          docker-compose -f docker_compose_ci.yml ps
          current_epoch="$(date -u +%s)"
          elapsed_seconds="$(($current_epoch-$start_epoch))"
          echo "Elapsed seconds: ${elapsed_seconds}"
        done

    # Be careful, if services aren't given sufficient time to initialize the tests will fail.
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        # This is python 3
        python -m pip install --upgrade pip
        pip install -r ${GITHUB_WORKSPACE}/tb-houston-service/tests/requirements.txt

    - name: Test with pytest
      run: |
        cd ${GITHUB_WORKSPACE}/tb-houston-service/tests
        pip install pytest
        #HOUSTON_SERVICE_URL="0.0.0.0:3000" pytest

    - name: Stop Docker Compose
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/tb-houston-service
        docker-compose -f docker_compose_ci.yml down 
