name: Lint and Format Check

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout current branch
        uses: actions/checkout@v2

      - name: Setup latest Python
        uses: actions/setup-python@v2

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: Setup flake8
        run: |
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Format Check with black
        uses: psf/black@stable
